import type { Metadata } from 'next'
import '@/app/globals.css'
import AuthGuard from '@/components/AuthGuard'

export const metadata: Metadata = {
  title: 'MacDash',
  description: 'Generated by Ishant Yadav',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-gray-400 font-plus-jakarta text-sm/[22px] font-normal text-gray antialiased">
        <AuthGuard>{children}</AuthGuard>
      </body>
    </html>
  )
}
